
export interface PlayerStat {
  player_id: number;
  ff_minerals_lost_army : number
    ff_minerals_lost_economy : number
    ff_minerals_lost_technology : number
    ff_vespene_lost_army : number
    ff_vespene_lost_economy : number
    ff_vespene_lost_technology : number
    food_made : number
    food_used : number
    frame : number
    minerals_collection_rate : number
    minerals_current : number
    minerals_killed : number
    minerals_killed_army : number
    minerals_killed_economy : number
    minerals_killed_technology : number
    minerals_lost : number
    minerals_lost_army : number
    minerals_lost_economy : number
    minerals_lost_technology : number
    minerals_used_active_forces : number
    minerals_used_current : number
    minerals_used_current_army : number
    minerals_used_current_economy : number
    minerals_used_current_technology : number
    minerals_used_in_progress : number
    minerals_used_in_progress_army : number
    minerals_used_in_progress_economy : number
    minerals_used_in_progress_technology : number
    pid : number
    resources_killed : number
    resources_lost : number
    resources_used_current : number
    resources_used_in_progress : number
    second : number
    vespene_collection_rate : number
    vespene_current : number
    vespene_killed : number
    vespene_killed_army : number
    vespene_killed_economy : number
    vespene_killed_technology : number
    vespene_lost : number
    vespene_lost_army : number
    vespene_lost_economy : number
    vespene_lost_technology : number
    vespene_used_active_forces : number
    vespene_used_current : number
    vespene_used_current_army : number
    vespene_used_current_economy : number
    vespene_used_current_technology : number
    vespene_used_in_progress : number
    vespene_used_in_progress_army : number
    vespene_used_in_progress_economy : number
    vespene_used_in_progress_technology : number
    workers_active_count : number
    player_game_id: number
}
